[workspace]
resolver = "2"
members = [
    "app/*",
    "base",
    "controls",
    "game",
    "graphics",
    "lobby/*",
    "server",
]

[profile.release-wasm]
inherits = "release"
lto = true
opt-level = "z"
