[tasks.build-wasm]
command = "cargo"
args = ["build", "-p", "*_app_wasm", "--target", "wasm32-unknown-unknown"]
workspace = false

[tasks.build-wasm-release]
command = "cargo"
args = ["build", "-p", "*_app_wasm", "--target", "wasm32-unknown-unknown", "--release-wasm"]
workspace = false

[tasks.build-web]
command = "wasm-bindgen"
args = ["--target", "deno", "--no-typescript", "target/wasm32-unknown-unknown/debug/cricket_pong_app_wasm.wasm", "--out-dir", "wasm", "--out-name", "cricket_pong"]
dependencies = ["build-wasm"]
workspace = false

[tasks.build-web-release]
command = "wasm-bindgen"
args = ["--target", "deno", "--no-typescript", "target/wasm32-unknown-unknown/release/cricket_pong_app_wasm.wasm", "--out-dir", "wasm", "--out-name", "cricket_pong"]
dependencies = ["build-wasm-release"]
workspace = false

[tasks.build-web-prod]
command = "wasm-opt"
args = ["-Oz", "-o", "wasm/cricket_pong_bg.wasm", "wasm/cricket_pong_bg.wasm"]
dependencies = ["build-web-release"]
workspace = false
